# USB Support
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="Ellie VR Tracker"
CONFIG_USB_DEVICE_VID=0x2FE3
CONFIG_USB_DEVICE_PID=0x0001

CONFIG_USB_DEVICE_HID=y
CONFIG_USB_HID_DEVICE_COUNT=1

CONFIG_GPIO=y

CONFIG_I2C=y
CONFIG_SPI=y

CONFIG_SENSOR=y

CONFIG_ESB=y

CONFIG_I2S=y
CONFIG_LED_STRIP=y

CONFIG_FUEL_GAUGE=y
