CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_HID_SUPPORT=y

CONFIG_GPIO=y

CONFIG_I2C=y
CONFIG_SPI=y

CONFIG_SENSOR=y

CONFIG_ESB=y
CONFIG_ESB_MAX_PAYLOAD_LENGTH=32
CONFIG_ESB_PIPE_COUNT=8

CONFIG_COUNTER=y

CONFIG_I2S=y
CONFIG_LED_STRIP=y

CONFIG_FUEL_GAUGE=y
